### ISSUE TITLE
Few minor suggestions

### ISSUE THREAD

**Issue by karlicoss** [MatthieuBizien/roam-to-git#2]
Hi. Just tried it -- awesome tool, especially thanks for keeping everything tidy and modular! 
My usecase is exporting all Roam Research data into a JSON (I want to use it in other tools), and I was pleased to be able to use your library for that in a [very straightforward way](https://github.com/karlicoss/exports/blob/master/roamresearch.py) :)

I've figured none of my suggestions are worthy separate issues so piled under a single one. Hopefully it's ok.

1. Add `export` to the repository topics? That way if someone searches for 'roam export' your repository would pop up. ('backup'/'export' are pretty interchangeable)

2. The library logs in stdout, which might be annoying if someone tries to use it with other tools, it's better to log in stderr. I've [hacked it](https://github.com/karlicoss/exports/blob/f20120b8c609b56abcfe525142c62e9f170aa96e/roamresearch.py#L48) in my script, but would be nice to use `print(..., file=sys.stderr)` throughtout the library instead?

3. The call to [`patch_pyppeteer`](https://github.com/MatthieuBizien/roam-to-git/blob/master/roam_to_git/scrapping.py#L10) -- do you think it makes sense to simply move it inside `download_rr_archive`? Then could remove the call from `main` too.

4. Expose a method to simply return the JSON? E.g `scrapping.export_json(...) -> str`.
    
    The JSON contains everything the user potentially needs for exporting notes, and if the library exposes it, the export would be as easy as.

    It requires extracting the json from zip, but `zipfile` library is standard, so that wouldn't create any extra dependencies. It's just [four lines of code](https://github.com/karlicoss/exports/blob/f20120b8c609b56abcfe525142c62e9f170aa96e/roamresearch.py#L51-L54). But I'd understand if you'd rather not complicate your module.

5. Add `username`,`passwords` as arguments for [`Config`](https://github.com/MatthieuBizien/roam-to-git/blob/1fd3ddc3949fa8bc8f052c761787e09a8c93b5d8/roam_to_git/scrapping.py#L32-L34)?

   E.g it would look like:

   ```
   def __init__(self, database: Optional[str], debug: bool, user: str=os.environ.get("ROAMRESEARCH_USER"), password: str=os.environ.get("ROAMRESERACH_PASSWORD")):
       self.user = user
       self.password = password
       assert self.user
       assert self.password
   ```

   That way you won't have to necessarily use environment variables for passing username/password. Not a biggie, but sometimes it's more convenient.

Let me know what you think, and I'm happy to contribute the changes you approve!

**Comment by MatthieuBizien** [comment]
> Hi. Just tried it -- awesome tool, especially thanks for keeping everything tidy and modular!
My usecase is exporting all Roam Research data into a JSON (I want to use it in other tools), and I was pleased to be able to use your library for that in a very straightforward way :)

Thanks 😃 

> I've figured none of my suggestions are worthy separate issues so piled under a single one. Hopefully it's ok.

> 1. Add export to the repository topics? That way if someone searches for 'roam export' your repository would pop up. ('backup'/'export' are pretty interchangeable)

Done, thanks!

>2. The library logs in stdout, which might be annoying if someone tries to use it with other tools, it's better to log in stderr. I've hacked it in my script, but would be nice to use print(..., file=sys.stderr) throughtout the library instead?

I have added [Loguru](https://github.com/Delgan/loguru) for logging, you can now just configure it.

> 3. The call to patch_pyppeteer -- do you think it makes sense to simply move it inside download_rr_archive? Then could remove the call from main too.

`patch_pyppeteer` is not really idempotent, and it may be not needed in another version of pypetter (even if it is not maintained), so I'd rather not.

> 4. Expose a method to simply return the JSON? E.g scrapping.export_json(...) -> str.
> The JSON contains everything the user potentially needs for exporting notes, and if the library exposes it, the export would be as easy as.
> It requires extracting the json from zip, but zipfile library is standard, so that wouldn't create any extra dependencies. It's just four lines of code. But I'd understand if you'd rather not complicate your module.

That's a good idea, it could be done by making `download_rr_archive` return a `Dict[str, str]`, so it would not change the quantity of code.

> Add username,passwords as arguments for Config?

Why not, if you need it.

> Let me know what you think, and I'm happy to contribute the changes you approve!

You're my guest 😃
