### ISSUE TITLE
Backup fails 1-2 times per day

### ISSUE THREAD

**Issue by jskn** [MatthieuBizien/roam-to-git#27]
I get "Run failed for master" at least once per day for my workflow of Roam Research backup. The message I get is "Process completed with exit code 1".

Any idea of what this issue is related to? Does it have anything to do with how often backup is done?

**Comment by pcuellar** [comment]
I am on Mac 10.15.6 Catalina and keep getting this error several times. After multiple attempts, backup starts working with no apparent reason. I am running manual backup, but setting it up through GitHub actions yields the same result.

**Comment by pcuellar** [comment]
**Update**: for some reason the `.env` file on my `/notes` folder was reset and didn't have my credentials. I updated it and it's now working. I figured out this being the issue by running `roam-to-git --debug notes/` and watching the automated flow on Chromium.

**Comment by jskn** [comment]
I use Github Actions with the credentials in secrets. I've changed cridentials and update the Github secrets but still get's the same error. Don't know if it's because scraping is done too often.

**Comment by MatthieuBizien** [comment]
You have to edit the file `.github/workflows/main.yml`, commit and push.

Example for running the backup every 4 hours: `cron: "0 */4 * * *"`

**Comment by jskn** [comment]
@MatthieuBizien Thanks! Will try that.
