### ISSUE TITLE
formatting does not works for Markdown heading

### ISSUE THREAD

**Issue by JimmyLv** [MatthieuBizien/roam-to-git#30]
```
- ## Heading2
  - list1
  - list2
- ### Heading3
  - list1
  - list2
```

=> Expected Behavior: 

```
## Heading2
  - list1
  - list2
### Heading3
  - list1
  - list2
```

**Comment by MatthieuBizien** [comment]
Removing the bullets does not work, as `    - list1\n    - list2` will be considered as code. Note that we use 4 spaces before the bullets, as in Roam export.

Demo:
```
## Heading2
    - list1
    - list2
```
## Heading2
    - list1
    - list2

It would also complicate some cases, like if list1 is an indented title.
