### ISSUE TITLE
Namespaced pages are missing in formatted output

### ISSUE THREAD

**Issue by michalochman** [MatthieuBizien/roam-to-git#31]
**Describe the bug**
While browsing the snapshot of my database I have noticed that namespaced pages are missing in formatted output directory, but are available in markdown output directory.

**To Reproduce**
1. Create namespaced page, e.g. Roam Research/Change Log
2. Wait for the automated snapshot to finish.
3. Browse `formatted` directory.
4. See that the namespaced page is missing.

**Expected behavior**
The namespaced page should be exported to `formatted` output using the same directory snapshot as `markdown` output.

**Additional context**
I've created few pages to illustrate the issue in the [demo dabatase](https://roamresearch.com/#/app/roam-to-git-demo):
- Parent page (namespace): https://roamresearch.com/#/app/roam-to-git-demo/page/rno73NVkf
- Child page: https://roamresearch.com/#/app/roam-to-git-demo/page/YYHGSmq-B
- Another child: https://roamresearch.com/#/app/roam-to-git-demo/page/zgOHoe0pV

Also, see [snapshot commit](https://github.com/MatthieuBizien/roam-to-git-demo/commit/25e865c079376ace133979eb6d159ddab8e21c65).

**Comment by MatthieuBizien** [comment]
Fixed with c6867cb, like #32.

Demo https://github.com/MatthieuBizien/roam-to-git-demo/blob/master/formatted/Roam%20Research/Support.md
