### ISSUE TITLE
Slashes in page names are incorrectly assumed to be folder separators in the script

### ISSUE THREAD

**Issue by phildenhoff** [MatthieuBizien/roam-to-git#32]
**Describe the bug**
Slashes in page names are incorrectly assumed to be folder separators in the script. 

When running as a GitHub Action, a leading forward slash in a page name creates an error running the script. It seems to try to create a file at the filesystem root ("/"), instead of in the local directory, which is denied.

For example, I had a page called "/r/PersonalFinanceCanada" related to the subreddit, which caused the below error. When I was able to run it, a page called "What to do / what to prioritize" ended up creating a folder called "What to do " and a file called " what to prioritize.md".

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a new page in your Roam database with a leading "/"
2. Execute the backup script
3. The script will fail, trying to write to a file at the root of the filesystem instead of in the local directory.

**Expected behavior**
Page names should not affect the location of the file when backed up to git. Pages with special characters in their name ("/", mainly) should have those characters escaped.

**Traceback**
https://gist.github.com/phildenhoff/e408ba8e8dbd89dfc158e774b8527570

```
2020-07-14T15:46:34.5618020Z PermissionError: [Errno 13] Permission denied: '/r'
```

**Run `roam-to-git --debug notes/` and report what you get.**
It should open a Chrome front-end, an do the scrapping. The repository content will not be modified. If applicable, add screenshots to help explain your problem.

**Please complete the following information:**
- OS: GitHub
- Do you use Github Action? Yes
- Do you use multiple Roam databases? No
- Did roam-to-git previously work for you? When precisely did it stop working? No. Until I removed the leading slash on the page, roam-to-git did not work. However, removing that slash **did** make the program work.
- Do backup runs work intermittently? As far as I can tell, they always work now.

**Additional context**

**Comment by phildenhoff** [comment]
Thanks for fixing! I'm looking forward to all my /-starting pages working again :)

**Comment by MatthieuBizien** [comment]
Hi @phildenhoff, thanks for the report. This is a known bug, I just fixed it. Everything was saved in markdown/, but not in formatted/.

On my personal notes repository, I have "2,985 additions and 0 deletions", so it was useful :) 

Feel free to re-open the issue if something is broken.
