### ISSUE TITLE
Umlauts break "formatted" links

### ISSUE THREAD

**Issue by benwf** [MatthieuBizien/roam-to-git#34]
**Describe the bug**  
While pages with umlauts get exported just fine (nice!), the conversion to formatted markdown notes stumbles upon them and breaks the conversion to a link right before them and truncates everything after.

**To Reproduce**  
1. create a tag or link to a page with an umlaut
2. have it exported
3. have a look at the `formatted` / compare it to raw markdown

**Expected behavior**  
The whole tag / link should be converted.

**Please complete the following information:**  
- OS: macOS
- Do you use Github Action? _yes_
- Do you use multiple Roam databases? _yes_
- Does roam-to-git use to work for you? When precisely did it stopped to work? _yes_ (it didn't stop)
- Does some backup runs are still working? _yes_ (only affects conversion to formatted)

**Comparison:**  

Raw:
<img width="132" alt="01_raw" src="https://user-images.githubusercontent.com/3187653/87661510-03ef7000-c761-11ea-8401-24aeeb3f9cef.png">

Formatted:
<img width="273" alt="02_formatted" src="https://user-images.githubusercontent.com/3187653/87661518-0782f700-c761-11ea-9524-8e2f5574aa9d.png">

**Unrelated:**  
I thank you soooo much for Roam to Git. Without this GitHub Action, I wouldn't have the confidence to actually use Roam. This is a so good functionality it belongs right into Roam's core.

**Comment by benwf** [comment]
_Update_: this appears to happen only in the 

`Themen::`

header, like this:

`Themen:: [Denken](<Denken.md>) [Lernen](<Lernen.md>) [Glaubens](<Glaubens.md>)ätze [Definitionen](<Definitionen.md>) #[💡2](<💡2.md>)`

It's fine everywhere else, even if an attribute itself has an umlaut.

**Comment by benwf** [comment]
Further digging around a bit it appears this is a Roam problem, not on roam-to-git's end:

When importing a file that contains umlauts in its file name into Roam, it appears that Roam itself messes them up with a special and hidden character in front of the umlaut.

Manually fixing the titles with umlauts (for reference: on the page view, in the title, selecting the character before, the umlaut itself, and the character after, and retyping them) on my end fixed this problem.

Hence closed.

**Comment by MatthieuBizien** [comment]
Thanks for the digging!
