### ISSUE TITLE
[remote rejected] master -> master (refusing to allow an OAuth App to create or update workflow

### ISSUE THREAD

**Issue by incandescentman** [MatthieuBizien/roam-to-git#38]
**Describe the bug**
When doing git push, I get this error message:
 ! [remote rejected] master -> master (refusing to allow an OAuth App to create or update workflow `.github/workflows/main.yml` without `workflow` scope)

**To Reproduce**
1. git push --set-upstream origin master

**Expected behavior**

**Traceback**
Please use http://gist.github.com/ or similar, and report the last line here.

**Run `roam-to-git --debug notes/` and report what you get.**
! [remote rejected] master -> master (refusing to allow an OAuth App to create or update workflow `.github/workflows/main.yml` without `workflow` scope)

**Please complete the following information:**
- OS: [MacOs]
- Do you use Github Action? No
- Do you use multiple Roam databases? No
- Does roam-to-git use to work for you? When precisely did it stopped to work? Never worked
- Does some backup runs are still working? No

**Additional context**

**Comment by MatthieuBizien** [comment]
Hi @incandescentman, it looks like an issue of your account with Github Action. Google suggest me [this link](https://techdailychronicle.com/github-actions-error-refusing-to-allow-an-oauth-app-to-create-or-update-workflow/), does it helps?

If you're unable to debug it, maybe https://github.com/elstudio/actions-js-build could help you.

Please post the solution when you find it for futur users 😄
