### ISSUE TITLE
Backup fails - may be dupe of #46 & #47

### ISSUE THREAD

**Issue by jmsidhu** [MatthieuBizien/roam-to-git#51]
**Describe the bug**

Backup from actions has begun to fail repeatedly after 200+ successful commits.

**To Reproduce**
1. Either allow Git Action to run as scheduled or manual run Git Action

2. See error in Gist here: https://gist.github.com/jmsidhu/875f9f89d5d8592cd463791168aa697c

**Expected behavior**
Expected action to run per design

**Traceback**
https://gist.github.com/jmsidhu/875f9f89d5d8592cd463791168aa697c

**Run `roam-to-git --debug notes/` and report what you get.**
Not quite sure how to do this

**Please complete the following information:**
- OS: Win10 & iOS
- Do you use Github Action? Yes
- Do you use multiple Roam databases? No
- Does roam-to-git use to work for you? It used to
- When precisely did it stopped to work? This morning, 9/15
- Does some backup runs are still working? Consecutive backups are failing

**Comment by everruler12** [comment]
Starting to have the same issue

**Comment by jchaudhuri1** [comment]
I am also having the same issue. I get error notification by email: Run failed for master (xxxxxxx). And an annotation: Process completed with exit code 1. 

Like other posters, have had no problems for many commits, but suddenly it's failing.

**Comment by keikhcheung** [comment]
> I am also having the same issue. I get error notification by email: Run failed for master (xxxxxxx). And an annotation: Process completed with exit code 1.

I occasionally have the same problem before. But since about a week ago, it has become a usual event. Almost happening once in every second hour.

**Comment by kerim** [comment]
Getting the same thing. Any idea what might be causing it?

**Comment by nicolevanderhoeven** [comment]
Backups are failing for me as well, with the same error (`Process completed with exit code 1`). Here's a bit more information, as my setup is a bit different from the OP's:
**OS**: macOS Catalina 10.15.7 (19H2)
**Do you use Github Action?** Yes
**Do you use multiple Roam databases?** Yes
**Does roam-to-git use to work for you?** It's never worked - this is the first time I'm trying it.
**Are some backup runs still working?** No, they're all failing.

**Comment by everruler12** [comment]
@nicolevanderhoeven At the bottom of my guide are a few things to check for in troubleshooting:
https://eriknewhard.com/blog/backup-roam-in-github

The exit code is not enough to tell what's wrong. A full log would be needed. You download your log like this:
![_roam-to-git log](https://user-images.githubusercontent.com/64292121/101585920-023b7880-399e-11eb-89c6-4c1790445005.gif)

**Comment by kerim** [comment]
Curious if anyone is able to get a successful backup every time? I get about one failure every 10 runs. That is good enough, but just curious if there are any tweaks that can make it run more reliably? (I set it to run every 2 hours instead of every hour, and that seemed to help a bit...)

**Comment by MatthieuBizien** [comment]
The backup errors should be fixed by #92 🍾. 

I'm closing that issue, but feel free to re-open it if you get new errors.
