### ISSUE TITLE
What to put as password for Roam account created via Google (no password)?

### ISSUE THREAD

**Issue by skotzko** [MatthieuBizien/roam-to-git#53]
**Describe the bug**
I am trying to set this up, but I have no Roam password as I created my Roam account via Google Auth sign-in.

**To Reproduce**
1. Go to https://roamresearch.com/#/signup
2. Create an account by clicking "Or sign up with Google" 
3. Create account via Google

**Expected behavior**
I don't know what to put in for my `ROAMRESEARCH_PASSWORD` key

**Traceback**
n/a

**Please complete the following information:**
- OS: MacOS Catalina
- Do you use Github Action? I would but don't know what to put for this secret
- Do you use multiple Roam databases? No
- Does roam-to-git use to work for you? When precisely did it stopped to work?
- Does some backup runs are still working?

**Comment by cjharr** [comment]
You need to set a password for your roam database , by clicking "Forgot password." This is mentioned in the Debug section of the READ.ME file. https://github.com/MatthieuBizien/roam-to-git/blob/master/README.md

**Comment by skotzko** [comment]
Ah, so it is. Sorry I missed that. Thank you.
