### ISSUE TITLE
Backup error after some while in Github

### ISSUE THREAD

**Issue by boydean41** [MatthieuBizien/roam-to-git#61]
Thanks for an amazing code enabling saving of Roam database
Github has been backing up Roam for me for a few months now

I am a bit of a novice however - how do I find the total time it has been backing up each month and the total volume of data that has been used. I have started to get regular backup errors and I suspect it may be because my allocated quota for storage has been reached.

If this is the case, is there a way to improve the script such that it deletes earlier backups - or will this not actually solve the problem? I guess it actually depends whether the script only backs up the changes between backups or whether it backs up the entire database each time.

Thanks for your thoughts and guidance about how to best approach.

Alternatively - is there a way to have the file saved to my computer instead of within Github?

Any solutions would be much appreciated

**Comment by anthrolisp** [comment]
I have two of my graphs set to back up every four hours. All backups from both have failed since around midday 10/20/2020. Before that, more often than not they would complete. Thanks in advance!

**Comment by everruler12** [comment]
Fixed in #59 waiting to be merged. For temporary fix, in your main.yml file, replace:

`pip install git+https://github.com/MatthieuBizien/roam-to-git.git`

with

`pip install git+https://github.com/mbakht/roam-to-git.git@patch-1`

**Comment by boydean41** [comment]
> Fixed in #59 waiting to be merged. For temporary fix, in your main.yml file, replace:
> `pip install git+https://github.com/MatthieuBizien/roam-to-git.git`
> with
> `pip install git+https://github.com/mbakht/roam-to-git.git@patch-1`

Thanks @everruler12 - what does the new code actually do Erik?

**Comment by everruler12** [comment]
> Thanks @everruler12 - what does the new code actually do Erik?

You can click the #59 link to see the explanation

**Comment by MatthieuBizien** [comment]
The backup errors should be fixed by #92 🍾. 

I'm closing that issue, but feel free to re-open it if you get new errors.
