### ISSUE TITLE
Support EDN?

### ISSUE THREAD

**Issue by TDHTTTT** [MatthieuBizien/roam-to-git#63]
**Is your feature request related to a problem? Please describe.**
Since Roam has a new export format, EDN, maybe we want to support it as well?

**Describe the solution you'd like**
Just upload it like we did with JSON.

**Describe alternatives you've considered**
no

**Additional context**
EDN seems to have more information then json/markdown as it preserves the block IDs.

**Comment by pmbauer** [comment]
roam has an EDN export option, but no option to import EDN yet

**Comment by rushikb** [comment]
> roam has an EDN export option, but no option to import EDN yet

But it is possible to restore a graph in it's entirely using EDN— Just had to do this because of the readwise issues

**Comment by pmbauer** [comment]
> > roam has an EDN export option, but no option to import EDN yet
> 
> 
> 
> But it is possible to restore a graph in it's entirely using EDN— Just had to do this because of the readwise issues

Yes, as of 2 days ago.
