### ISSUE TITLE
Consecutive Backup Fails after long run of successful backups

### ISSUE THREAD

**Issue by jmsidhu** [MatthieuBizien/roam-to-git#73]
**Describe the bug**
I have seen 17 consecutive backup fails in a row occur on the hourly action I have set.  There are two variety of errors.  The first appears to be a time out error after the action runs for 15 min or so.  The second is a exit code 1 error.  I have append URLs with the logs below

**To Reproduce**

   Either allow Git Action to run as scheduled or manual run Git Action

   See 'timeout error' log here: [](https://gist.github.com/jmsidhu/a7a404a216538d9cd9cc5d0349309b72)
   See 'exit code 1' error log here: [](https://gist.github.com/jmsidhu/50d06462ce60667d6c6e1fb30b557b91)

**Expected behavior**
 
   I expected the action to run per design.  I have made no modifications since the last successful run.

**Traceback**
   Two errors, either:

       `Error: Process completed with exit code 1.`

   or 

       `Error: The operation was canceled.`

**Run `roam-to-git --debug notes/` and report what you get.**
    **Not sure how or where to run this command.**  

**Please complete the following information:**
   OS: **Win10 & iOS**
   Do you use Github Action? **Yes**
   Do you use multiple Roam databases? **Yes**
   Does roam-to-git use to work for you? **It used to**
   When precisely did it stopped to work? **11/20/2020 at approx. 10:00am EST**
   Does some backup runs are still working? **Consecutive backups are failing**

**Comment by ErikBjare** [comment]
Having the same issue, but mine started Nov 17th. I think it might merely have to do with the size of the graph.

Getting `AssertionError: All roads leads to Roam, but that one is too long. Try again when Roam servers are faster.`

**Comment by ErikBjare** [comment]
See #50 for a possible solution

**Comment by philkuz** [comment]
@ErikBjare your solution was to switch from google auth to the User,Pass auth? Seems weird that google auth should send the above error. Did you link the wrong issue?

**Comment by ErikBjare** [comment]
@philkuz Nope, correct issue. It indeed solved the problem, see the many duplicate issues I linked.

**Comment by MatthieuBizien** [comment]
The backup errors should be fixed by #92 🍾. 

I'm closing that issue, but feel free to re-open it if you get new errors.
