### ISSUE TITLE
Backups failing to run - please help!

### ISSUE THREAD

**Issue by karisgriley** [MatthieuBizien/roam-to-git#75]
**Describe the bug**
I've just set up a Roam-Git workflow yesterday (first time user). I've deleted my GitHub account to start over 3 times, and created new google passwords for my Roam account 3 times. The backups continue to fail.

When I click on press/re-run jobs, I still get either:
AssertionError: All roads leads to Roam, but that one is too long. Try again when Roam servers are faster.
108

Or

ERROR    | __main__:<module>:33 - An error has been caught in function '<module>', process 'MainProcess' (XXXX), thread 'MainThread' (XXXXXXXXXXXXXXX):
[I HAVE DELETED THE NUMBERS]

OR

Error: Process completed with exit code 1.

**To Reproduce**

**Expected behavior**

**Traceback**
Please use http://gist.github.com/ or similar, and report the last line here.
Where do I find this?

**Run `roam-to-git --debug notes/` and report what you get.**
It should open a Chrome front-end, an do the scrapping. The repository content will not be modified. If applicable, add screenshots to help explain your problem.

**Please complete the following information:**
- OS: [e.g. MacOs, Linux] macOS Catalina 10.15.7
- Do you use Github Action? Yes 
- Do you use multiple Roam databases? No
- Does roam-to-git use to work for you? When precisely did it stopped to work? I just joined yesterday; 18 hourly consecutive failures. In other words, it's never worked, and I've deleted my GitHub account and Roam google password to start over multiple times. 
- Does some backup runs are still working?

**Additional context**

How long should title pages on Roam be? I have removed every / from every title page in Roam as Erik Newhard advised. 

I have followed this:
NB: as of October 21st 2020, this code is broken because of a change at Roam. Github user mbakht has created a temporary fix:
locate the following line in the code:
pip install git+https://github.com/MatthieuBizien/roam-to-git.git
and replace it with:
pip install git+https://github.com/mbakht/roam-to-git.git@patch-1

And I have followed this:
Note: As of October 1st, the default branch name for new repos was changed from "master" to "main". The branch name here needs to match your repo's branch name

**Comment by everruler12** [comment]
I've been getting the same error every so often (more so recently), but not every hour.

> How long should title pages on Roam be?

Less than 255 characters should prevent any problems with the markdown export.

> I have removed every / from every title page in Roam as Erik Newhard advised.

Note that `/` is only an issue as the first character in a page title (and perhaps double `//`). Slashes are useful for [namespacing](https://forum.roamresearch.com/t/namespaces-how-do-they-work/276).

**Comment by karisgriley** [comment]
Thanks! I will try this and see how it goes.
It's backing up now, for some reason....

KARIS GRACE

**Comment by MatthieuBizien** [comment]
The backup errors should be fixed by #92 🍾. 

I'm closing that issue, but feel free to re-open it if you get new errors.
