### ISSUE TITLE
Consistent backup error (resolved)

### ISSUE THREAD

**Issue by wogong** [MatthieuBizien/roam-to-git#76]
**Describe the bug**
Consistent backup error after many successful backups.

**Expected behavior**

**Traceback**
`[E:pyppeteer.connection] connection unexpectedly closed`

full log here https://gist.github.com/wogong/2de0bcba77e5d18de0fa75e425f7003a

**Please complete the following information:**
- Do you use Github Action?
Yes
- Do you use multiple Roam databases?
No
- Does roam-to-git use to work for you? When precisely did it stopped to work?
Yes
- Does some backup runs are still working?

**Additional context**
When I change `runs-on: ubuntu-latest` to `runs-on: ubuntu-18.04` in `.github/workflows/main.yml`, backup task works as before.
I don't know what causes the problem, neither know why this can work.
Just post it here incase anyone needs it.

**Comment by KrisAcharya** [comment]
Thank you very much! This fixed the exact same issue I have having as well!
