### ISSUE TITLE
Issue with "Remote End Closed Connection..."

### ISSUE THREAD

**Issue by aakar** [MatthieuBizien/roam-to-git#80]
I created a bug a few months ago: https://github.com/MatthieuBizien/roam-to-git/issues/22 and then sadly I disappeared.  I've retried running a GH Action and am still seeing the same timeout.  So I decided to try and install the local version and run it manually with "--debug".  

The browser loads and it eventually gets to the download dialog and downloads the file, however, the script crashes before it finishes downloading.  It raises the following error response:
`raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response`

This is the start of the stacktrace.  Happy to provide more but didn't want to muddy the waters:
`Traceback (most recent call last):
> File "/Users/aakar/.local/bin/roam-to-git", line 8, in <module>
    sys.exit(main())
    │   │    └ <function main at 0x1112604c0>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/Users/aakar/.local/pipx/venvs/roam-to-git/lib/python3.9/site-packages/roam_to_git/__main__.py", line 76, in main
    scrap(markdown_zip_path, json_zip_path, config)
    │     │                  │              └ <roam_to_git.scrapping.Config object at 0x11125b5e0>
    │     │                  └ PosixPath('/var/folders/6h/q5_s8mlj73q23kzbzbd80pd40000gn/T/tmp4pq8o75v')
    │     └ PosixPath('/var/folders/6h/q5_s8mlj73q23kzbzbd80pd40000gn/T/tmpgif50_go')`

**Comment by everruler12** [comment]
You're not using a Google account for logging in, correct? Can you try re-entering your Secrets?

**Comment by aakar** [comment]
Nope.  I reverted from a Google account to creating my own password and using that account.

**Comment by MatthieuBizien** [comment]
The backup errors should be fixed by #92 🍾. 

I'm closing that issue, but feel free to re-open it if you get new errors.
