### ISSUE TITLE
Process completed with exit code 1.

### ISSUE THREAD

**Issue by kerim** [MatthieuBizien/roam-to-git#84]
**Describe the bug**
Was working fine until 5 to 6 days ago. (Would only fail about 1 in 10 times.) Since then, it has failed every single time. Error is:

`Process completed with exit code 1.`

**To Reproduce**
I didn't do anything different, was working fine beforel

**Expected behavior**
Backup

**Traceback**
Please use http://gist.github.com/ or similar, and report the last line here.

Don't understand this request.

**Run `roam-to-git --debug notes/` and report what you get.**
It should open a Chrome front-end, an do the scrapping. The repository content will not be modified. If applicable, add screenshots to help explain your problem.

Don't know/understand how to do this.

**Please complete the following information:**
- OS: [e.g. MacOs, Linux] I'm on a Mac, but seems irrelevant? 
- Do you use Github Action? Yes.
- Do you use multiple Roam databases? No.
- Does roam-to-git use to work for you? When precisely did it stopped to work? See above. 
- Does some backup runs are still working? No.

**Additional context**

**Comment by bobmhughes** [comment]
I am also receiving the same error message "Process completed with exit code 1". I just set up my Roam backup using the instructions at https://kuvee.medium.com/a-step-by-step-guide-to-backing-up-your-roam-research-database-356107fe82ee 
OS: Windows 10
Do you use Github Action? Yes.
Do you use multiple Roam databases? No.
Does roam-to-git use to work for you? I just set it up today and it failed on the first run
When precisely did it stopped to work? December 20, 2020
Does some backup runs are still working? No

**Comment by kerim** [comment]
I tried creating starting fresh with a new script and GitHub repository, but the same problem: "Process completed with exit code 1."

**Comment by bobmhughes** [comment]
Here is the log file in text format from the most recent failed backup with the error code "Process completed with exit code 1". I have added an empty line between the sections of the backup log for sake of clarity.

https://www.dropbox.com/s/nmjhw93346euqek/Roam%20backup%20using%20GitHub%20error%20log.txt?dl=0

Thanks for your help with this error!

**Comment by harishravichandar** [comment]
Experiencing the same issue!

_OS:_ Windows 10
_Do you use Github Action?_ Yes.
_Do you use multiple Roam databases?_ No.
_Does roam-to-git use to work for you?_ Yes, have been using it since Sep.
_When precisely did it stopped to work?_ December 20, 2020
_Does some backup runs are still working?_ No, fails consistently.

**Comment by kerim** [comment]
Still not working for me. Fails every time.

**Comment by bobmhughes** [comment]
Same here, fails every time with the same error code. 

Thanks in advance for help solving this issue

**Comment by everruler12** [comment]
@kerim All errors end with `Process completed with exit code 1`. Please attach your log file. (You can check at the end of [my guide](https://eriknewhard.com/blog/backup-roam-in-github) for where to find your log files.)

@bobmhughes From your error log, there's an issue with it logging in. Try checking [my guide](https://eriknewhard.com/blog/backup-roam-in-github) to see if it sheds some light. Double check that your ROAMRESEARCH_DATABASE value is just the name of your graph, and not a URL.

**Comment by bobmhughes** [comment]
@everruler12 Thanks for the suggestion to "Double check that your ROAMRESEARCH_DATABASE value is just the name of your graph, and not a URL". I don't know if this was entered wrong or not as when you go to update it, the previous value does not show. I also checked the "All workflows" page and it turns out that the backup is not failing every time. I incorrectly assumed that it was failing every time as I have received so many "backup failed" emails. I didn't realize that I would not receive an email if the backup was successful. When there is an error, I see this in the log "AssertionError: All roads lead to Roam, but that one is too long. Try again when Roam servers are faster. Error: Process completed with exit code 1." I also noticed in the log file that the backup was trying to access "https://roamresearch.com/#/app/***" which doesn't make sense to me.

**Comment by everruler12** [comment]
@bobmhughes Your graph name is a Secret, that's why it uses *** in place of it. I've been getting the same kind of error every so often. I don't know what causes it. It may be Roam timing out. As long as most hourly runs are successful, these errors can be ignored.

**Comment by kerim** [comment]
@everruler12 Thanks. I was able to find the error on my own and it is working again. What happened is that I had imported some notes (via Readwise) that had a double colon "::" (probably an OCR error in the original PDF) at the end of a huge block of text. Roam treated this as an attribute, hence a page name, and the backup script was giving an error for having a page name that was too long. I wonder if the backup script could be made more robust so that errors like this don't interrupt the backup?

**Comment by bobmhughes** [comment]
@everruler12 It looks like I am getting an 83% success rate with my backups.  The most common errors are Assertion and Network errors

**Comment by bobmhughes** [comment]
The errors are back, although I haven’t changed the code one bit. I haven’t had a successful backup in about 36 hours. How about you?

 

Thanks,

Bob

**Comment by everruler12** [comment]
Most of my hourly backups are still successful, with about 3 errors per day.

**Comment by bobmhughes** [comment]
Here is the relevant excerpt from the latest failed backup, which is the same error as I have received every time for the last almost two days now.

 

AssertionError: All roads leads to Roam, but that one is too long. Try again when Roam servers are faster.

Error: Process completed with exit code 1.

 

Any suggestions?

 

Thanks, 

 

Bob

**Comment by everruler12** [comment]
Is the time out happening between `Wait for interface to load` and `Closing browser markdown`? Also see #76

**Comment by yosephplex** [comment]
Error: Process completed with exit code 1.
