### ISSUE TITLE
Backup failing since ~ 3 days ago with "connection unexpectedly closed" after filling in the email

### ISSUE THREAD

**Issue by Stvad** [MatthieuBizien/roam-to-git#88]
**Describe the bug**
Starting since around 3 days ago my GitHub actions WF is failing with "connection unexpectedly closed" after filling in the email

**Traceback**
https://gist.github.com/Stvad/a4b70d744de11d1f7a3b26d7b30823bf

**Please complete the following information:**
- Do you use Github Action? - Yes
- Do you use multiple Roam databases? - Yes
- Does roam-to-git use to work for you? When precisely did it stopped to work? - Yes ~3 days ago
- Does some backup runs are still working? - It seems like there was 1 successful run ~Yesterday

**Comment by everruler12** [comment]
Check out my new solution https://github.com/everruler12/roam2github-demo

**Comment by MatthieuBizien** [comment]
The backup errors should be fixed by #92 🍾. 

I'm closing that issue, but feel free to re-open it if you get new errors.
