### ISSUE TITLE
How can you call roam-to-git from another python script?

### ISSUE THREAD

**Issue by 8bitgentleman** [MatthieuBizien/roam-to-git#90]
I am looking to integrate roam-to-git into a larger roam project and I am trying to figure out how to import and trigger the backup via another python script.  Any know how to do that?

**Comment by 8bitgentleman** [comment]
```import sys```
```sys.argv += ['--skip-git', 'notes', "-f", "edn"]```

**Comment by MatthieuBizien** [comment]
You can just import roam_to_git! You would have to duplicate some of the logic of __main__.py.
