### ISSUE TITLE
Unable to locate element: input[name='email'] (starting ~2 days ago)

### ISSUE THREAD

**Issue by Stvad** [MatthieuBizien/roam-to-git#99]
**Describe the bug**
My GH Workflow started to fail ~70% of time with the above error.

See the full trace at https://gist.github.com/Stvad/01ddf6c6d389e7b96be59196918f3ced
 
**Please complete the following information:**
- OS: Linux
- Do you use Github Action? - Yes
- Do you use multiple Roam databases? - I have multiple db's but backing up just one
- Does roam-to-git use to work for you? When precisely did it stopped to work? - it worked a lot more reliably up untill ~2 days ago
- Does some backup runs are still working? - Yes

**Comment by paulantoine** [comment]
hello, I have the same problem 4,3, 1 and 0 days ago, but it worked ok 2 days ago.
before that it had been working ok for over 20 days.
no change in github config, no significant change in roam other than editing notes
only 1 database

**Comment by ErikPlachta** [comment]
Thank you for this release
